### ISSUE TITLE
Website not showing any image

### ISSUE THREAD

**Issue by ngohungphuc** [sindresorhus/plash-bing-photo-of-the-day#1]
In https://bing-photo-of-the-day.netlify.app/ there is only blank black screen. Can you check it. Thanks

**Comment by sindresorhus** [comment]
It shows fine for me.

**Comment by ngohungphuc** [comment]
<img width="1436" alt="Schermafbeelding 2021-06-21 om 19 12 03" src="https://user-images.githubusercontent.com/13591213/122759817-9464f780-d2c4-11eb-8344-a6eba6bc6d99.png">

Here is the screenshot. I dont see any console error too.
